IF
	HPPercentLT(Myself,20)
	!HasItem("POTN55",Myself)
	False()
	!Range(NearestMyGroupOfType,15)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,49767)
		EscapeArea()
END

IF
	!HPPercentLT(Myself,20)
	!Range(LastSeenBy(Myself),8)
THEN
	RESPONSE #100
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	!HPPercentLT(Myself,20)
	Range(LastSeenBy(Myself),8)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END