IF
  HPPercentLT(Myself,20)
  !HasItem("POTN55",Myself)
  !Range(NearestMyGroupOfType,15)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,49767)
    EscapeArea()
END

IF
  ActionListEmpty()
  !Range(LastSeenBy(Myself),10)
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(LastSeenBy(Myself),45)
END

IF
  ActionListEmpty()
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),45)
END