IF
	HaveSpellRES("SPCL913") 
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("Evasion","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("Evasion","LOCALS",18)
		SetGlobalTimer("DrankPotionTimer","LOCALS",6)
		SpellRES("SPCL913",Myself) 
END

IF
	HaveSpellRES("SPCL917") 
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("AvoidDeath","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("AvoidDeath","LOCALS",30)
		SetGlobalTimer("DrankPotionTimer","LOCALS",6)
		SpellRES("SPCL917",Myself) 
END