IF
	!Allegiance(LastSeenBy(Myself),GOODCUTOFF)
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	HaveSpellRES("SPCL916") 
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	Range(LastSeenBy(Myself),10)
	OR(2)
		StateCheck(Myself,STATE_INVISIBLE)
		StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	!GlobalTimerNotExpired("Assassinate","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("Assassinate","LOCALS",6)
		SetGlobalTimer("DrankPotionTimer","LOCALS",6)
		SpellRES("SPCL916",Myself) 
END

IF
	OR(2)
		StateCheck(Myself,STATE_INVISIBLE)
		StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		MoveToObject(LastSeenBy(Myself))
		AttackReevaluate(LastSeenBy(Myself),15)
		RunAwayFrom(LastSeenBy(Myself),30)
END

IF
	Range(LastSeenBy(Myself),10)
	HPPercentLT(Myself,20)
	OR(2)
		HasItem("POTN55",Myself) 
		Range(NearestMyGroupOfType,25)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		RunAwayFrom(LastSeenBy(Myself),45)
		SetInterrupt(TRUE)
END

IF
	Range(LastSeenBy(Myself),10)
	HPPercentLT(Myself,20)
	!HasItem("POTN55",Myself) 
	False()
	!Range([ANYONE],15)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,49767) 
		EscapeArea()
END

IF
	True()
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END