IF
  OR(2)
  !Allegiance(LastSeenBy(Myself),GOODCUTOFF)
  !See([GOODCUTOFF])
  Range(Player1,20)
THEN
  RESPONSE #100
    RandomWalkContinuous()
END

IF
  OR(2)
  !Allegiance(LastSeenBy(Myself),GOODCUTOFF)
  !See([GOODCUTOFF])
  !Range(Player1,20)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  HaveSpellRES("SPCL916")
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  Range(LastSeenBy(Myself),6)
  OR(2)
  StateCheck(Myself,STATE_INVISIBLE)
  StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !GlobalTimerNotExpired("Assassinate","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Assassinate","LOCALS",6)
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    SpellRES("SPCL916",Myself)
END

IF
  !Range(LastSeenBy(Myself),6)
  OR(2)
  StateCheck(Myself,STATE_INVISIBLE)
  StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    MoveToObject(LastSeenBy(Myself))
END

IF
  Range(LastSeenBy(Myself),6)
  OR(2)
  StateCheck(Myself,STATE_INVISIBLE)
  StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),30)
END

IF
  ActionListEmpty()
  Range(LastSeenBy(Myself),10)
  HPPercentLT(Myself,20)
  OR(2)
  HasItem("POTN55",Myself)
  Range(NearestMyGroupOfType,25)
THEN
  RESPONSE #100
		SetInterrupt(FALSE)
    RunAwayFrom(LastSeenBy(Myself),45)
		SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  Range(LastSeenBy(Myself),10)
  HPPercentLT(Myself,20)
  !HasItem("POTN55",Myself)
  OR(2)
  !See([ANYONE])
  !Range([ANYONE],15)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,49767)
    EscapeArea()
END

IF
  ActionListEmpty()
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  Range(NearestEnemyOf(Myself),5)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),60)
  RESPONSE #50
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),45)
END

IF
  ActionListEmpty()
  RandomNum(2,1)
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !Range(NearestEnemyOf(Myself),15)
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(NearestEnemyOf(Myself),45)
END

IF
  ActionListEmpty()
  RandomNum(2,1)
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !Range(NearestEnemyOf(Myself),5)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),30)
END

IF
  ActionListEmpty()
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),45)
END