IF
  Range(Lastseenby(Myself),5)
  NumCreatureGT(Nearestmygroupoftype([ANYONE.GENERAL_ITEM.0.FIGHTER_ALL]),0)
  Range(Nearestmygroupoftype([ANYONE.GENERAL_ITEM.0.FIGHTER_ALL]),10)
  OR(5)
    HasItem("BLAKBLAD",Myself)
    HasItem("PHANBLAD",Myself)
    CheckStatLT(Myself,10,THAC0)
    CheckStatLT(Myself,0,ARMORCLASS)
    !HaveAnySpells()
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(Lastseenby(Myself),30)
END