IF
  See(Nearestenemyof(Myself))
  HaveSpell(WIZARD_MISLEAD)
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Myself,STATE_POISONED)
  !GlobalTimerNotExpired("SpecialDefenseUp","LOCALS")
  GlobalLT("NumDefenses","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobalTimer("SpecialDefenseUp","LOCALS",72)
    IncrementGlobal("NumDefenses","LOCALS",1)
    Spell(Myself,WIZARD_MISLEAD)
    Continue()
END