IF
  ActionListEmpty()
  Global("DefenseSpell","LOCALS",1)
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_IMPROVED_MANTLE)
  !GlobalTimerNotExpired("WeaponDefense_On","LOCALS")
  OR(2)
    Range(NearestEnemyOf(Myself),4)
    AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    SetGlobalTimer("WeaponDefense_On","LOCALS",24)
    SetGlobal("DefenseSpell","LOCALS",0)
    Spell(Myself,WIZARD_IMPROVED_MANTLE)
END