IF
  HaveSpell(WIZARD_POWER_WORD_SILENCE)
  OR(6)
    Class(Lastseenby(Myself),DRUID_ALL)
    Class(Lastseenby(Myself),BARD)
    Class(Lastseenby(Myself),CLERIC_ALL)
    Class(Lastseenby(Myself),LONG_BOW)
    Class(Lastseenby(Myself),SORCERER)
    InPartySlot(Lastseenby(Myself),0)
  !HasBounceEffects(Lastseenby(Myself))
  !StateCheck(Lastseenby(Myself),STATE_SILENCED)
THEN
  RESPONSE #100
    Spell(Lastseenby(Myself),WIZARD_POWER_WORD_SILENCE)
END