IF
  ActionListEmpty()
  Global("DefenseSpell","LOCALS",1)
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_SIMULACRUM)
  !GlobalTimerNotExpired("SpecialDefenseUp","LOCALS")
  GlobalLT("NumDefenses","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobalTimer("SpecialDefenseUp","LOCALS",96)
    IncrementGlobal("NumDefenses","LOCALS",1)
    SetGlobal("DefenseSpell","LOCALS",0)
    Spell(Myself,WIZARD_SIMULACRUM)
    Continue()
END