IF
  ActionListEmpty()
  Global("DefenseSpell","LOCALS",1)
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("FireShield_On","LOCALS")
  GlobalLT("NumDefenses","LOCALS",2)
  HaveSpell(WIZARD_FIRE_SHIELD_RED)
THEN
  RESPONSE #100
    SetGlobalTimer("FireShield_On","LOCALS",60)
    IncrementGlobal("NumDefenses","LOCALS",1)
    SetGlobal("DefenseSpell","LOCALS",0)
    Spell(Myself,WIZARD_FIRE_SHIELD_RED)
END