IF
  Die()
THEN
  RESPONSE #100
    Shout(ALERT)
END

IF
  BreakingPoint()
THEN
  RESPONSE #100
    DisplayStringHead(Myself,49766)
    Shout(ASSIST)
  RESPONSE #100
    DisplayStringHead(Myself,49767)
    Shout(ASSIST)
  RESPONSE #100
    DisplayStringHead(Myself,49768)
    Shout(ASSIST)
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Shout(ALERT)
    Enemy()
END

IF
  ActionListEmpty()
  See([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  Global("ShoutedAlert","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("ShoutedAlert","LOCALS",1)
    Shout(ALERT)
    Continue()
END

IF
  Heard([ANYONE],ALERT)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  See(NearestEnemyOf(Myself))
  See([EVILCUTOFF])
  InMyGroup(LastSeenBy(Myself))
  HPPercentLT(Myself,25)
  HPGT(Myself,1)
  !Range(LastSeenBy(Myself),8)
  !GlobalTimerNotExpired("Whined","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Whined","LOCALS",6)
    DisplayStringHead(Myself,46151)
    Shout(ASSIST)
  RESPONSE #100
    SetGlobalTimer("Whined","LOCALS",6)
    DisplayStringHead(Myself,49763)
    Shout(ASSIST)
  RESPONSE #100
    SetGlobalTimer("Whined","LOCALS",6)
    DisplayStringHead(Myself,49764)
    Shout(ASSIST)
  RESPONSE #100
    SetGlobalTimer("Whined","LOCALS",6)
    DisplayStringHead(Myself,49765)
    Shout(ASSIST)
END

IF
  HPPercentLT(Myself,50)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN55",Myself)
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    DisplayStringHead(Myself,46150)
    UseItem("POTN55",Myself)
END

IF
  HPPercentLT(Myself,50)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN52",Myself)
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    DisplayStringHead(Myself,46150)
    UseItem("POTN52",Myself)
END

IF
  See(NearestEnemyOf(Myself))
  OR(2)
  Range(NearestMyGroupOfType,20)
  See(NearestMyGroupOfType([0.0.0.CLERIC_ALL]))
  HPPercentLT(Myself,35)
  !GlobalTimerNotExpired("CalledForHealing","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("CalledForHealing","LOCALS",6)
    DisplayStringHead(Myself,72808)
    Shout(HEALME)
    Continue()
END

IF
  Heard(NearestMyGroupOfType,HEALME)
  !StateCheck(LastHeardBy(Myself),STATE_DEAD)
  HPPercentGT(Myself,75)
  See(LastHeardBy(Myself))
  Range(LastHeardBy(Myself),10)
  !Range(NearestMyGroupOfType([0.0.0.CLERIC_ALL]),20)
  !NumItemsGT("POTN55",LastHeardBy(Myself),0)
  NumItemsGT("POTN55",Myself,1)
  !GlobalTimerNotExpired("GaveAwayPotion","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("GaveAwayPotion","LOCALS",12)
    DisplayStringHead(Myself,72809)
    GiveItem("POTN55",LastHeardBy(Myself))
    SmallWait(2)
    ActionOverride(LastHeardBy(Myself),DisplayStringHead(Myself,73896))
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_HASTED)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN14",Myself)
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    DisplayStringHead(Myself,46150)
    UseItem("POTN14",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
  HasItem("POTN10",Myself)
THEN
  RESPONSE #100
    SetGlobalTimer("DrankPotionTimer","LOCALS",6)
    DisplayStringHead(Myself,46150)
    UseItem("POTN10",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !GlobalTimerNotExpired("RingTimer","LOCALS")
  HasItem("RING05",Myself)
THEN
  RESPONSE #100
    SetGlobalTimer("RingTimer","LOCALS",6)
    DisplayStringHead(Myself,46150)
    UseItem("RING05",Myself)
END

IF
  ActionListEmpty()
  HaveSpellRES("SPCL913")
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("Evasion","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Evasion","LOCALS",18)
    SpellRES("SPCL913",Myself)
END

IF
  ActionListEmpty()
  HaveSpellRES("SPCL917")
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("AvoidDeath","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("AvoidDeath","LOCALS",30)
    SpellRES("SPCL917",Myself)
END

IF
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    NoAction()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Continue()
END

IF
  OR(3)
  See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.BARD]))
  See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]))
  See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
THEN
  RESPONSE #100
    Continue()
END

IF
  OR(3)
  See(NearestEnemyOfType([GOODCUTOFF.0.0.BARD]))
  See(NearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]))
  See(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
THEN
  RESPONSE #100
    Continue()
END

IF
  OR(2)
  See(ThirdNearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
  See(ThirdNearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
THEN
  RESPONSE #100
    Continue()
END

IF
  OR(2)
  See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
  See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
THEN
  RESPONSE #100
    Continue()
END

IF
  OR(2)
  See(NearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
  See(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
THEN
  RESPONSE #100
    Continue()
END

IF
  Heard(NearestMyGroupOfType(Myself),ASSIST)
  !StateCheck(LastHeardBy(Myself),STATE_DEAD)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_INVISIBLE)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_CHARMED)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_HELPLESS)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_SLEEPING)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_STUNNED)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_CONFUSED)
  See(LastAttackerOf(LastHeardBy(Myself)))
THEN
  RESPONSE #100
    Continue()
END

IF
  ActionListEmpty()
  Heard(NearestMyGroupOfType,ASSIST)
  See(LastHeardBy(Myself))
  !See(LastAttackerOf(LastHeardBy(Myself)))
  !StateCheck(LastHeardBy(Myself),STATE_DEAD)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_INVISIBLE)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_CHARMED)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_HELPLESS)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_SLEEPING)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_STUNNED)
  !StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_CONFUSED)
  !HPPercentLT(Myself,50)
  !Range(NearestEnemyOf(Myself),5)
THEN
  RESPONSE #100
    MoveToObject(LastHeardBy(Myself))
END

IF
  AttackedBy([ANYONE],DEFAULT)
  See(LastAttackerOf(Myself))
THEN
  RESPONSE #100
    Continue()
END

IF
  Range(NearestEnemyOf(Myself),4)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    Continue()
END

IF
  !Allegiance(LastSeenBy(Myself),GOODCUTOFF)
  See([GOODCUTOFF])
THEN
  RESPONSE #100
    MoveToObject([GOODCUTOFF])
END

IF
  OR(2)
  !Allegiance(LastSeenBy(Myself),GOODCUTOFF)
  !See([GOODCUTOFF])
  Range(Player1,20)
THEN
  RESPONSE #100
    RandomWalkContinuous()
END

IF
  OR(2)
  !Allegiance(LastSeenBy(Myself),GOODCUTOFF)
  !See([GOODCUTOFF])
  !Range(Player1,20)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  HaveSpellRES("SPCL916")
  Range(LastSeenBy(Myself),6)
  OR(2)
  StateCheck(Myself,STATE_INVISIBLE)
  StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !GlobalTimerNotExpired("Assassinate","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Assassinate","LOCALS",6)
    SpellRES("SPCL916",Myself)
END

IF
  !Range(LastSeenBy(Myself),6)
  OR(2)
  StateCheck(Myself,STATE_INVISIBLE)
  StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    MoveToObject(LastSeenBy(Myself))
END

IF
  Range(LastSeenBy(Myself),6)
  OR(2)
  StateCheck(Myself,STATE_INVISIBLE)
  StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),30)
END

IF
  ActionListEmpty()
  Range(LastSeenBy(Myself),10)
  HPPercentLT(Myself,20)
  OR(2)
  HasItem("POTN55",Myself)
  Range(NearestMyGroupOfType,25)
THEN
  RESPONSE #100
    RunAwayFrom(LastSeenBy(Myself),45)
END

IF
  ActionListEmpty()
  Range(NearestEnemyOf(Myself),10)
  HPPercentLT(Myself,20)
  !HasItem("POTN55",Myself)
  OR(2)
  !See([ANYONE])
  !Range([ANYONE],15)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,49767)
    EscapeArea()
END

IF
  ActionListEmpty()
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  Range(NearestEnemyOf(Myself),5)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),60)
  RESPONSE #50
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),45)
END

IF
  ActionListEmpty()
  RandomNum(2,1)
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !Range(NearestEnemyOf(Myself),15)
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(NearestEnemyOf(Myself),45)
END

IF
  ActionListEmpty()
  RandomNum(2,1)
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !Range(NearestEnemyOf(Myself),5)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),30)
END

IF
  ActionListEmpty()
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),45)
END

