IF
  ActionListEmpty()
  Range(LastSeenBy(Myself),10)
  HPPercentLT(Myself,20)
  !HasItem("POTN55",Myself)
  OR(2)
  !See([ANYONE])
  !Range([ANYONE],15)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,49767)
    EscapeArea()
END

IF
  ActionListEmpty()
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  Range(NearestEnemyOf(Myself),5)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),60)
  RESPONSE #50
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),45)
END

IF
  ActionListEmpty()
  RandomNum(2,1)
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !Range(NearestEnemyOf(Myself),15)
THEN
  RESPONSE #100
    EquipRanged()
    AttackReevaluate(NearestEnemyOf(Myself),45)
END

IF
  ActionListEmpty()
  RandomNum(2,1)
  !StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !Range(NearestEnemyOf(Myself),5)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),30)
END

IF
  ActionListEmpty()
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(LastSeenBy(Myself),45)
END