DEFINE_ACTION_FUNCTION  ~update_epilogues~
	STR_VAR
	"filepath" = ~~
BEGIN
	COPY - ~%filepath%~  ~%filepath%~
  COUNT_2DA_ROWS 2 "rows_cnt_nscp"
  FOR( cntg=0; cntg<"%rows_cnt_nscp%"; cntg=cntg+1 ) BEGIN
    READ_2DA_ENTRY cntg  0 2 "2daNAME"
    READ_2DA_ENTRY cntg  1 2 "StringNBR"
		INNER_ACTION BEGIN
			COPY_EXISTING ~%2daNAME%.2da~ ~override~
				SET_2DA_ENTRY 4 2 1 ~EpilgoueString~
				REPLACE ~EpilgoueString~ ( AT StringNBR )
				BUT_ONLY
		END
	END
END
