IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)
    SetGlobal("ImoenHurt","GLOBAL",1)
    CreateVisualEffectObject("SPFIREPI","Imoen2")
    SmallWait(8)
    CreateVisualEffectObject("SPGFLSH1","Imoen2")
    ActionOverride("Imoen2",PlayDead(75))
    Wait(2)
    ActionOverride("Imoen2",LeaveParty())
    ActionOverride("Imoen2",SetDialogue("IMOEN25P"))
    ActionOverride("Imoen2",StartDialogNoSet(Player1))
END
